# Generated by Django 4.2 on 2023-09-11 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.CreateModel(
            name='FitnessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
